### ISSUE TITLE
无法找到模块“swiper”的声明文件

### ISSUE THREAD

**Issue by Crownico** [themusecatcher/vue-amazing-ui#1]
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/41910836/bad2f86c-54dc-4912-ae99-01950d527db5)
swiper 版本：9.3.2

请问这个问题该怎么解决？

**Comment by themusecatcher** [comment]
| |
Mr.Dear
|
|
***@***.***
|
你是否安装了swiper插件呢？安装之后即可正常使用SFC
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月26日 02:04 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1) |


swiper 版本：9.3.2

请问这个问题该怎么解决？

**Comment by Crownico** [comment]
安装了，功能是没有问题的。就是编辑器会有上述提示，并且控制台会有警告信息





Lesl
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "themusecatcher/vue-amazing-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1)





 
 
 
 
 | |
 Mr.Dear
 |
 |
 ***@***.***
 |
 你是否安装了swiper插件呢？安装之后即可正常使用SFC
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年06月26日 02:04 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt; |
 | 主题 | [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1) |
 
 
 swiper 版本：9.3.2
 
 请问这个问题该怎么解决？

**Comment by themusecatcher** [comment]
这个你可以搜一下 自行解决试试
| |
Mr.Dear
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月26日 22:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1) |

安装了，功能是没有问题的。就是编辑器会有上述提示，并且控制台会有警告信息





Lesl
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "themusecatcher/vue-amazing-ui" ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1)









| |
Mr.Dear
|
|
***@***.***
|
你是否安装了swiper插件呢？安装之后即可正常使用SFC
---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2023年06月26日 02:04 |
| 收件人 | ***@***.***&gt; |
| 抄送人 | ***@***.***&gt; |
| 主题 | [themusecatcher/vue-amazing-ui] 无法找到模块“swiper”的声明文件 (Issue #1) |


swiper 版本：9.3.2

请问这个问题该怎么解决？
