### ISSUE TITLE
瀑布流问题

### ISSUE THREAD

**Issue by ccc-fox** [themusecatcher/vue-amazing-ui#12]
瀑布流在使用中动态加载第二次数据高度重置导致滚动条滚动到最上面

**Comment by themusecatcher** [comment]
动态加载第二次数据 你是指在原有数据的基础上再次请求接口拼接新的数据吧
目前瀑布流并没有适配这种场景，只要 images 原数据发生变化  都会重置瀑布流，重新计算

**Comment by ccc-fox** [comment]
okk，谢谢大佬
