### ISSUE TITLE
descriptions 组件有bug

### ISSUE THREAD

**Issue by gcming** [themusecatcher/vue-amazing-ui#13]
静态数据没问题，但是当请求接口，在使用 descriptions 组件不渲染，并且slot的内容比如button等组件事件丢失

**Comment by themusecatcher** [comment]
感谢指出这个问题！目前已经修复，请尝试使用 vue-amazing-ui@1.0.29+ ，如有问题和建议，欢迎随时留言😁😁

**Comment by gcming** [comment]
<template>
  <div style="padding:20px;">
  <Descriptions title="User Info" bordered>
    <DescriptionsItem label="Product">Cloud Database</DescriptionsItem>
    <DescriptionsItem label="Billing Mode">Prepaid</DescriptionsItem>
    <DescriptionsItem label="Automatic Renewal">YES</DescriptionsItem>
    <DescriptionsItem label="Order time">2018-04-24 18:00:00</DescriptionsItem>
    <DescriptionsItem label="Usage Time" :span="2">2030-04-24 18:00:00</DescriptionsItem>
    <DescriptionsItem label="Negotiated Amount">$80.00</DescriptionsItem>
    <DescriptionsItem label="Discount">$20.00</DescriptionsItem>
    <DescriptionsItem label="Official Receipts">$60.00</DescriptionsItem>
    <DescriptionsItem label="测试1">{{ info.name }}</DescriptionsItem>
    <DescriptionsItem label="测试2">{{ info.sex }}</DescriptionsItem>
    <DescriptionsItem label="测试3">
      <div @click="handleClick">点我</div>
    </DescriptionsItem>
  </Descriptions>
  </div>
</template>
<script setup lang="ts">
  import { ref,onMounted } from "vue";
  const info=ref({
    name:'',
    sex:'1'
  })


  onMounted(()=>{
   //模拟请求
    getinfo();
  })

  const getinfo= ()=>{
      setTimeout(() => {
        info.value.name='张三'
        info.value.sex='2'
      }, 1000);
  }

  const handleClick=()=>{
    console.log('点击事件')
  }


</script>  现在用的1.0.30还是存在这个问题，info.value数据发生改变的时候不会重新渲染table，同样 click事件不生效

**Comment by gcming** [comment]
`<template>
  <div style="padding:20px;">
  <Descriptions title="User Info" bordered>
    <DescriptionsItem label="Product">Cloud Database</DescriptionsItem>
    <DescriptionsItem label="Billing Mode">Prepaid</DescriptionsItem>
    <DescriptionsItem label="Automatic Renewal">YES</DescriptionsItem>
    <DescriptionsItem label="Order time">2018-04-24 18:00:00</DescriptionsItem>
    <DescriptionsItem label="Usage Time" :span="2">2030-04-24 18:00:00</DescriptionsItem>
    <DescriptionsItem label="Negotiated Amount">$80.00</DescriptionsItem>
    <DescriptionsItem label="Discount">$20.00</DescriptionsItem>
    <DescriptionsItem label="Official Receipts">$60.00</DescriptionsItem>
    <DescriptionsItem label="测试1">{{ info.name }}</DescriptionsItem>
    <DescriptionsItem label="测试2">{{ info.sex }}</DescriptionsItem>
    <DescriptionsItem label="测试3">
      <div @click="handleClick">点我</div>
    </DescriptionsItem>
  </Descriptions>
  </div>
</template>
<script setup lang="ts">
  import { ref,onMounted } from "vue";
  const info=ref({
    name:'',
    sex:'1'
  })
  onMounted(()=>{
   //模拟请求
    getinfo();
  })
  const getinfo= ()=>{
      setTimeout(() => {
        info.value.name='张三'
        info.value.sex='2'
      }, 1000);
  }
  const handleClick=()=>{
    console.log('点击事件')
  }
</script>`  问题还是存在，动态改变的数据不会重新渲染table，click点击事件不生效

**Comment by gcming** [comment]
> 感谢指出这个问题！目前已经修复，请尝试使用 vue-amazing-ui@1.0.29+ ，如有问题和建议，欢迎随时留言😁😁

![Uploading 微信图片_20240717160219.png…]()

   问题还是存在，现在用的是1.0.30,动态改变的数据不会重新渲染，click点击事件不生效

**Comment by gcming** [comment]
![微信图片_20240717160219](https://github.com/user-attachments/assets/73fdb71e-6b31-4d50-a0b9-ee124c0a24e4)
问题还是存在，现在用的是1.0.30,动态改变的数据不会重新渲染，click点击事件不生效

**Comment by themusecatcher** [comment]
请使用 vue-amazing-ui@1.1.0 试一下：动态修改数据；使用动态数据生成Item；内部组件点击事件，目前均已支持！有问题欢迎随时交流(๑•̀ㅂ•́)و✧

**Comment by gcming** [comment]
已经可以了，

> 请使用 vue-amazing-ui@1.1.0 试一下：动态修改数据；使用动态数据生成Item；内部组件点击事件，目前均已支持！有问题欢迎随时交流(๑•̀ㅂ•́)و✧
已经可以了
