### ISSUE TITLE
Ellipsis 组件不显示省略号的时候tooltip应该不要显示

### ISSUE THREAD

**Issue by LBC000** [themusecatcher/vue-amazing-ui#14]
如题. 如图
![image](https://github.com/user-attachments/assets/db2c1aea-fa57-41cf-81b6-4942b4b551fb)

**Comment by themusecatcher** [comment]
good question！已修复并更新，请使用尝试 @1.2.0 及以上版本

**Comment by LBC000** [comment]
> good question！已修复并更新，请使用尝试 @1.2.0 及以上版本

升级了. 有省略号后不显示tooltip

**Comment by themusecatcher** [comment]
有省略号不显示tooltip？ 文档样例并没出现这种情况，麻烦提供下原代码

**Comment by LBC000** [comment]
> 有省略号不显示tooltip？ 文档样例并没出现这种情况，麻烦提供下原代码

一开始全屏没有省略号, 缩小窗口导致省略的时候不显示tooltip. 如果一开始是小窗口省略是可以显示tooltip的.
```js
<Ellipsis line="2" :maxWidth="1058" >
        <div class="mt-[.375rem] mr-[3.125rem] text-[.75rem] text-[#fff]">
          本世纪头十年，随着全球造船市场逐渐东移，欧美等传统造船业纷纷转型，全球造船重心集中到太平洋东岸。中国及时承接了这次东移带来的机遇，逐渐与日本、韩国一起成为全球造船的三巨头。天时、地利、人和，中国造船在2010 年收获历史最好成绩：全国造船完工量、新承接船舶订单量、手持船舶订单量三项指标均领跑全球
        </div>
      </Ellipsis>

```
