### ISSUE TITLE
TextScroll 组件设置一条数据循环播放时, 播放完后等待再次播放时间太久了. 大概有5-6s才重新播放

### ISSUE THREAD

**Issue by LBC000** [themusecatcher/vue-amazing-ui#15]
![image](https://github.com/user-attachments/assets/75db21c4-ed04-4938-8bdd-7c6d6db88ab2)
![image](https://github.com/user-attachments/assets/be8e544c-000a-4a32-982b-50f9d034d3c0)

```js
<TextScroll
    single
    :gap="1"
    style="height: 100%"
    :scrollText="singleText"
    :textStyle="{ fontSize: '18px', color: '#0C7CE6', fontWeight: 400 }"
    :boardStyle="{ backgroundColor: 'transparent', boxShadow: 'none' }"
  />
```

**Comment by themusecatcher** [comment]
这不是组件的问题吧🤣
单条文字滚动这个功能逻辑是每条数据都占据整个宽度
你可以参考我的样例，如果文字比较少，就把宽度设置小一点，如果宽度比较大，就保证文字多一点
总之：保证文字宽度和轮播区域的宽度不要差太多，尽量接近，就不会有你说的这种问题

**Comment by LBC000** [comment]
> 这不是组件的问题吧🤣 单条文字滚动这个功能逻辑是每条数据都占据整个宽度 你可以参考我的样例，如果文字比较少，就把宽度设置小一点，如果宽度比较大，就保证文字多一点 总之：保证文字宽度和轮播区域的宽度不要差太多，尽量接近，就不会有你说的这种问题

宽度是不确定的哦. 根据窗口变化的. 然后一条长数据左右横向循环播放

**Comment by themusecatcher** [comment]
滚动区域尺寸变化相关问题已更新，请尝试使用 @1.3.0 及以上版本
