### ISSUE TITLE
项目很好很厉害，但...

### ISSUE THREAD

**Issue by mlkt** [themusecatcher/vue-amazing-ui#17]
这首页背景图是认真的吗？中间的字都看不清楚了
还有奇怪的渐变，像是刚学会做ppt的人把刚学会的“艺术字”特效加上去一样
建议至少这背景图和文字的对比度得改了，否则会被质疑审美和专业性，别的项目都是用VitePress原版的白背景和纯色是道理的。

![image](https://github.com/user-attachments/assets/dbb33457-8f20-4072-9a8e-ec8acae0811a)

没别的意思，就提个比较刺耳的建议。看了文档和代码，组件还是很漂亮和完善的，加油。

**Comment by themusecatcher** [comment]
有道理的，刚好文档首页也是时候做些调整了；欢迎尝试使用并提出更多宝贵建议！感谢🙏
