### ISSUE TITLE
TextScroll 鼠标移入的时候 Tooltip 能不能加一个显示属性. 不想显示的时候可以不显示

### ISSUE THREAD

**Issue by LBC000** [themusecatcher/vue-amazing-ui#18]
TextScroll 鼠标移入的时候 Tooltip 能不能加一个显示属性. 不想显示的时候可以不显示

![image](https://github.com/user-attachments/assets/6193e49b-3485-4ce4-b444-7e5f617702a7)

**Comment by LBC000** [comment]
![image](https://github.com/user-attachments/assets/c70f1972-251e-4787-8a1d-77c853093543)

**Comment by themusecatcher** [comment]
首先感谢建议！关于这个问题，感觉功能点太小 不至于单独加个属性控制，你如果特殊情况需要使用，可以考虑直接使用单文件组件
