### ISSUE TITLE
文字滚动 TextScroll 能否添加组件重载时滚动位置重置的功能

### ISSUE THREAD

**Issue by huangshun137** [themusecatcher/vue-amazing-ui#19]
目前想要的功能是有提示才显示这个文字滚动，但是下次来消息时显示的滚动位置好像还是上次的，看看是否能优化下；
然后可以的话是不是在加一个滚动次数，比如滚动n次后停止滚动，或者给个回调能控制；

**Comment by themusecatcher** [comment]
组件重载滚动位置重置，能否详细说下；
停止滚动这种有点偏特殊需求，你可以考虑使用单文件组件二次开发来解决

**Comment by huangshun137** [comment]
因为显示的文字是通过ws即时获取的，当获取到新的信息，希望能重新从头开始滚动显示新的文字，现在好像无法实现

**Comment by themusecatcher** [comment]
你可以试着监听数据源的变化，然后重置滚动即可

**Comment by huangshun137** [comment]
ok，我二次开发处理下
