### ISSUE TITLE
打包过程中扔出的警告

### ISSUE THREAD

**Issue by zeMingGit** [themusecatcher/vue-amazing-ui#20]
这个问题老哥看看吗？打包后的包页面上好像有一些东西被影响了，是最新的1.7.0
![image](https://github.com/user-attachments/assets/f7f19279-96e9-4017-bc1e-8b0dab53e799)

**Comment by themusecatcher** [comment]
你的环境，依赖和打包方式都详细描述下，信息有限无法判断

**Comment by zeMingGit** [comment]
我是在vitepress中使用了vue-amazing-ui，这儿是所有的内容
![image](https://github.com/user-attachments/assets/7f6169de-e0b7-4c27-82ee-680ea9d601f4)

**Comment by themusecatcher** [comment]
vitepress 中我也有用，是没问题的，你这个版本并不是最新的，请尝试下 1.7.0 呢

**Comment by zeMingGit** [comment]
试过不行1.7.0

**Comment by themusecatcher** [comment]
![image](https://github.com/user-attachments/assets/d249c9c6-1125-42b9-81a9-79254f7880df)
这是我在 vitepress 中的注册和使用，打包部署是没问题的，你参考下呢

**Comment by themusecatcher** [comment]
![image](https://github.com/user-attachments/assets/eec0aa44-8f53-461d-9899-d670960c4e8c)
这是我在 vitepress 中的注册和使用，打包部署是没问题的，你参考下呢

**Comment by zeMingGit** [comment]
好嘟

**Comment by zeMingGit** [comment]
试了还是不行，算了算了不用啦。难啊
