### ISSUE TITLE
水印问题

### ISSUE THREAD

**Issue by zeMingGit** [themusecatcher/vue-amazing-ui#25]
作者您好：

我希望水印这个组件可以增加一个props，可以更改水印的position。页面滚动的时候，水印是不会随着文档而一起滚动。

谢谢作者，thanks

**Comment by themusecatcher** [comment]
你好，水印可以跟随内容一起滚动，也可以不跟随内容一起滚动，你只需要调整水印渲染的的元素位置即可，比如一个可滚动父元素，一个内容很长的子元素在父元素里面，你把父元素整体都放到水印里，水印就不会跟随滚动；但如果把子元素放到水印里，水印就是跟随滚动的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月28日 13:28 |
| 收件人 | themusecatcher/vue-amazing-ui ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [themusecatcher/vue-amazing-ui] 水印问题 (Issue #25) |

作者您好：

我希望水印这个组件可以增加一个props，可以更改水印的position。页面滚动的时候，水印是不会随着文档而一起滚动。

谢谢作者，thanks

**Comment by zeMingGit** [comment]
![image](https://github.com/user-attachments/assets/1910520e-9594-4b97-9ac6-c9d124cf827c)
根据你的建议，我修改了我的vitepress的theme，但是并没有实现

**Comment by themusecatcher** [comment]
vitepress 这个滚动方式有点特殊，你看下就知道它的 html 高度是跟滚动内容高度一致的，所以才导致水印跟随滚动

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月28日 16:13 |
| 收件人 | themusecatcher/vue-amazing-ui ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [themusecatcher/vue-amazing-ui] 水印问题 (Issue #25) |

image.png (view on web)
根据你的建议，我修改了我的vitepress的theme，但是并没有实现

**Comment by zeMingGit** [comment]
明白啦，那就暂时没有什么好办法对吧。

我自己手搓了一个，position为fixed就可以解决：https://vlog-java.netlify.app/

**Comment by themusecatcher** [comment]
嗯 这样也可以 回头我优化下水印组件

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月28日 16:23 |
| 收件人 | themusecatcher/vue-amazing-ui ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [themusecatcher/vue-amazing-ui] 水印问题 (Issue #25) |

明白啦，那就暂时没有什么好办法对吧。

我自己手搓了一个，position为fixed就可以解决：https://vlog-java.netlify.app/

**Comment by zeMingGit** [comment]
thanks

**Comment by zeMingGit** [comment]
![image](https://github.com/user-attachments/assets/8e78c92c-7729-4225-b216-4a7f65a53f46)


作者您好，我看到了您更新了commit，2.0.3什么时候能得到更新~嘻嘻谢谢作者

**Comment by themusecatcher** [comment]
下周一我会更新组件库新版本，到时会把水印相关优化发布上去

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月29日 13:58 |
| 收件人 | themusecatcher/vue-amazing-ui ***@***.***> |
| 抄送人 | ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [themusecatcher/vue-amazing-ui] 水印问题 (Issue #25) |

image.png (view on web)

作者您好，我看到了您更新了commit，2.0.3什么时候能得到更新~嘻嘻谢谢作者

**Comment by themusecatcher** [comment]
水印组件已更新，可以尝试使用 2.0.4 及以上版本
