### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by zhaoyifan-admin** [themusecatcher/vue-amazing-ui#3]
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/72063245/a37d30be-13e7-4191-aa89-6673e8a9c88a)

引入组件就一直报错这个，这里的作用是做什么的？

**Comment by themusecatcher** [comment]
这个报错并不是我组件库里的东西(~_~💧)
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2023 17:13 |
| To | themusecatcher/vue-amazing-ui ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [themusecatcher/vue-amazing-ui] TypeError: Cannot read properties of null (reading 'isCE') (Issue #3) |


引入组件就一直报错这个，这里的作用是做什么的？
