### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by ChenQuan5** [themusecatcher/vue-amazing-ui#4]
功能实现,代码编辑页面报错,虽然不影响使用,但是看着不舒服
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/48345535/b8798ee0-6567-4bba-a9e0-be19f4c7f2c0)
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/48345535/f4a109ea-6c0b-480f-ba8d-3f24f69d320a)

**Comment by themusecatcher** [comment]
同样使用时，我这边并没有遇到你这种情况，考虑是否是编辑器插件导致的
<img width="691" alt="image" src="https://github.com/themusecatcher/vue-amazing-ui/assets/46012811/27780580-8dfc-40c0-a2f6-1ad575eb77c4">
