### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by wild-deer** [themusecatcher/vue-amazing-ui#6]
请问
1.对于这个项目之后的发展方向有什么想法吗
2.组件很好用，但是说明文档中可能缺少一些与对于组件库特色（与其他常见组件库不同的地方）的说明，对于一个想要了解和探索的开发者来说还是缺少一些吸引力，建议可以添加上，这样可能有更多的人感兴趣

**Comment by themusecatcher** [comment]
之后自然是不断完善就有组件和探索新的组件，人性化开箱即用至上，也欢迎你随时留言各种idea
添加组件库特色说明这个建议不错，收到！
