### ISSUE TITLE
文字滚动 TextScroll 组件  滚动速度不稳定

### ISSUE THREAD

**Issue by qhl100** [themusecatcher/vue-amazing-ui#7]
代码如下：
 <TextScroll interval="300" :scroll-text="singleText" single :font-size="13" :font-weight="80" color="#FF5B29" height="100px" background-color="#F4F6F8" width="100%" amount="1" @click="onClick" />

感觉是多个TAB页来回切换，滚动速度就变快了
![1b3ca6e4-ff53-4a3d-991f-b24572e811ce](https://github.com/themusecatcher/vue-amazing-ui/assets/45582360/275edd3c-42ab-4a63-aac0-f33b918c6551)
![bba5cae1-865d-455f-9f9e-792e28181c83](https://github.com/themusecatcher/vue-amazing-ui/assets/45582360/198039b2-4b62-4c5b-b5f8-e21ee7c02361)

**Comment by themusecatcher** [comment]
滚动速度默认是根据浏览器刷新率自动计算得出的：
fps: 60 对应 step: 1
fps: 120 对应 0.5
其余刷新率： stpe: 60/fps

**Comment by themusecatcher** [comment]
- 为了保证动画效果，组件动画执行使用的是requestAnimationFrame，该函数会严格根据浏览器刷新率执行动画；
- 如果无法解决相关问题，那你可以考虑使用固定step，结合setTimeout执行动画函数，这种方案缺点是动画可能会丢帧，不如前者流畅；
二者各有利弊，请自行权衡使用...

**Comment by themusecatcher** [comment]
<textScroll>组件已重构，执行速度不再依赖浏览器刷新率，可自行安装最新组件库尝试使用
