### ISSUE TITLE
无法使用CDN方式引入，报错信息如下

### ISSUE THREAD

**Issue by wocwin** [themusecatcher/vue-amazing-ui#8]
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/37534478/db5fecd2-08b5-4c4e-b46e-004d4d2ca0fc)

**Comment by themusecatcher** [comment]
引入方式是否有问题呢？确保成功引入并成功注册

**Comment by wocwin** [comment]
按README的方式在index.html文件中引入
<script src="https://unpkg.com/vue@3"></script>
<script src="https://unpkg.com/vue-amazing-ui@latest"></script>
直接在项目中使用vue-amazing-ui中的组件，报没有注册成功问题
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/37534478/defb42a5-a346-472e-ba23-5c839eb4e7cd)

**Comment by wocwin** [comment]
在index.html下面注册？
![image](https://github.com/themusecatcher/vue-amazing-ui/assets/37534478/b7cde023-dab1-436f-a904-b83274757459)
这样还是不行

**Comment by themusecatcher** [comment]
可以考虑采用npm安装这种主流方式来替代浏览器

**Comment by themusecatcher** [comment]
可以考虑使用npm这种主流安装方式代替浏览器引入

**Comment by wocwin** [comment]
了解
